### ISSUE TITLE
Check bài

### ISSUE THREAD

**Issue by HaiYenPham** [LinhNguyen2k/LinhNguyen2k.github.io#1]
https://github.com/LinhNguyen2k/LinhNguyen2k.github.io/blob/47ef96caafe3e492121dc3bae63e7982a7e8d5a7/index.html#L130

Bài ổn, phần kiến thức này lúc nào cũng cần dùng nên cố gắng làm nhuần nhuyễn nhé!
Hy vọng bài sau của em sẽ tốt hơn nữa!
Thân ái và quyết thắng <3

**Comment by LinhNguyen2k** [comment]
oke chị ưiiii
em cảm ơn chị ạ :3

Vào Th 2, 7 thg 10, 2019 vào lúc 22:56 Phạm Thị Hải Yến <
notifications@github.com> đã viết:
